### ISSUE TITLE
Move Conan package to conan-center

### ISSUE THREAD

**Issue by zamazan4ik** [Enhex/Deco#1]
Hello.
Thank you for your library and for Conan package.
But user should add your repo to remotes. Can you move the package to conan-center repo?

**Comment by Enhex** [comment]
Adding packages to conan-center requires a review process before a package is accepted:
http://docs.conan.io/en/latest/packaging/bintray/conan_center_guide.html

It's probably a good idea to wait until the library is more mature before submitting, considering currently it's very new.

**Comment by Enhex** [comment]
added to conan-center:
https://conan.io/center/deco
https://github.com/conan-io/conan-center-index/pull/9818
